# LT Samba AD - LIDORIO TECH
UserParameter=sambaad.ping,python3 /etc/zabbix/scripts/lt_samba_ad.py ping
UserParameter=sambaad.discover_dcs,python3 /etc/zabbix/scripts/lt_samba_ad.py discover_dcs
UserParameter=sambaad.fsmo,python3 /etc/zabbix/scripts/lt_samba_ad.py fsmo
UserParameter=sambaad.domain[*],python3 /etc/zabbix/scripts/lt_samba_ad.py domain "$1"
UserParameter=sambaad.accounts[*],python3 /etc/zabbix/scripts/lt_samba_ad.py accounts "$1"
UserParameter=sambaad.dc[*],python3 /etc/zabbix/scripts/lt_samba_ad.py dc "$1" "$2"
