# LT Samba FS - LIDORIO TECH
UserParameter=sambafs.ping,python3 /etc/zabbix/scripts/lt_samba_fs.py ping
UserParameter=sambafs.version,python3 /etc/zabbix/scripts/lt_samba_fs.py version
UserParameter=sambafs.health[*],python3 /etc/zabbix/scripts/lt_samba_fs.py health "$1"
UserParameter=sambafs.config,python3 /etc/zabbix/scripts/lt_samba_fs.py config
UserParameter=sambafs.discover_shares,python3 /etc/zabbix/scripts/lt_samba_fs.py discover_shares
UserParameter=sambafs.share[*],python3 /etc/zabbix/scripts/lt_samba_fs.py share_detail "$1" "$2"
