# OpenMediaVault Monitoring - LIDORIO TECH
UserParameter=omv.ping,/usr/bin/python3 /etc/zabbix/scripts/lt_omv.py ping
UserParameter=omv.discover.filesystems,/usr/bin/python3 /etc/zabbix/scripts/lt_omv.py discover_filesystems
UserParameter=omv.discover.disks,/usr/bin/python3 /etc/zabbix/scripts/lt_omv.py discover_disks
UserParameter=omv.fs[*],/usr/bin/python3 /etc/zabbix/scripts/lt_omv.py fs "$1" "$2"
UserParameter=omv.disk[*],/usr/bin/python3 /etc/zabbix/scripts/lt_omv.py disk "$1" "$2"
