# LT Bareos - LIDORIO TECH
UserParameter=bareos.catalog.ping,/etc/zabbix/scripts/lt_bareos.py ping
UserParameter=bareos.clients.discovery,/etc/zabbix/scripts/lt_bareos.py clients
UserParameter=bareos.pools.discovery,/etc/zabbix/scripts/lt_bareos.py pools
UserParameter=bareos.job[*],/etc/zabbix/scripts/lt_bareos.py job "$1" "$2" "$3"
UserParameter=bareos.client[*],/etc/zabbix/scripts/lt_bareos.py client "$1" "$2"
UserParameter=bareos.pool[*],/etc/zabbix/scripts/lt_bareos.py pool "$1" "$2"
