# RustFS Monitoring - LIDORIO TECH
UserParameter=rustfs.ping,/etc/zabbix/scripts/lt_rustfs.py ping
UserParameter=rustfs.health[*],/etc/zabbix/scripts/lt_rustfs.py health "$1"
UserParameter=rustfs.cluster[*],/etc/zabbix/scripts/lt_rustfs.py cluster "$1"
UserParameter=rustfs.discover.buckets,/etc/zabbix/scripts/lt_rustfs.py discover buckets
UserParameter=rustfs.bucket[*],/etc/zabbix/scripts/lt_rustfs.py bucket "$1" "$2"
UserParameter=rustfs.capacity[*],/etc/zabbix/scripts/lt_rustfs.py capacity "$1"
